### ISSUE TITLE
Import textbox is too small in certain browsers

### ISSUE THREAD

**Issue by salmasian** [OHDSI/Circe#20]
Using latest release version of Firefox in Linux, or latest release version of Safari in Mac, when you click on the **Import** button in the Concept Set editor, the textbox shown is very small. Screenshots available below:

Firefox:
![Firefox](http://i58.tinypic.com/eivx3c.png)

Safari:
![Safari](http://i58.tinypic.com/2yv10l1.png)

**Comment by chrisknoll** [comment]
Yes, a default value of something like 'Enter concept IDs here...' as the default text is needed here.

**Comment by salmasian** [comment]
That, and also a minimum width and height assigned to the text-box via CSS.

**Comment by chrisknoll** [comment]
I've changed this to be handled in a dialog.
