### ISSUE TITLE
Import button does not work in Firefox

### ISSUE THREAD

**Issue by salmasian** [OHDSI/Circe#21]
Using latest release version of Firefox (regardless of OS) when you click on the **Import** button in the Concept Sets editor, and type or copy-paste a concept ID and click on **Done** either nothing happens, or the concept ID is replaced with "undefined" (see screenshot). You will be stuck in this situation; even if you clear the textbox and press **Done** to get back to the previous state, nothing happens.

![Firefox](http://i58.tinypic.com/9i67pl.png)

**Comment by chrisknoll** [comment]
Do you see any other errors in the console log? It could be that this is happening due to some other error on the page.

**Comment by salmasian** [comment]
No errors are logged when I input a value and it is replaced with "undefined".

If I click on **Done** after the text is replaced with "undefined", of course I get an error logged reading _this.importValues(...) is undefined_

Same if I empty the box and click on **Done**.

**Comment by chrisknoll** [comment]
I've pushed a new version of this behavior that opens a dialog to get the concept IDs.  However, looking at the error you are reporting, i'm not sure why firefox is not resolving this.importValues, it's a model variable that should be found.  Anyways, I'm going to instsall firefox and see if it is related to browser specific behavior.

**Comment by chrisknoll** [comment]
I've tested this on firefox 38.0.1 and the dialog appears and the import works when i enter 0,1,2,3,4 in the textbox and click done.
