### ISSUE TITLE
'Concept selector' should show 'standard concept' field

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Circe#3]
When I click 'Add' from 'with gender of:' , the 'concept selector' opens up with the domain restricted to 'Gender', which is a very nice feature.  However, the list includes all standard and non-standard concepts.  It'd be nice to show the standard field to allow sorting/filtering on the value.

Many enhancements to concept selector would likely be addressed once CIRCE is fully integrated with HERMES, so perhaps these can be de-prioritized until that integration is complete.

**Comment by cgreich** [comment]
I would not wait. It is impossible for folks to guess whether a concept is standard or not. They will inevitably look for MedDRA concepts in the CONDITION_ERA table. In fact, standard_concept should be checked by default. Non-standard concepts are only needed when we come from a source concept.
