### ISSUE TITLE
Add a concept to a concept set

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Circe#30]
I am not able to add a concept to a concept set using a concept_id.
I know the concept ID that I want to be in the set. it is 378419. I know there was a tiny box to enter it and it is no longer there. I am using the public instance at http://www.ohdsi.org/web/circe/#/166

**Comment by chrisknoll** [comment]
The small import textbox was removed in favor of a larger dialog where (in the future) you can paste a longer list, separated by commas, returns, basically any white space. That's the future plan, but for now, it has to be a comma delimited list.  Just click import at the bottom (the upper import button is to import concept sets, bottom import is for individual concepts).
