### ISSUE TITLE
Condition occurence start date reverts to today's date after saving

### ISSUE THREAD

**Issue by mattlevine22** [OHDSI/Circe#42]
Use case:
Condition Occurrence start is On or After 2015-01-01.
Save.
Reverts to Today's date.

This happens whether I type the date manually or use the calendar selection tool.

**Comment by chrisknoll** [comment]
I'm sorry, but I'm not seeing this.  What is the browser you are using?  Also, is there any OS-level settings that would influence the date format parsing?  Such as regional settings?

**Comment by mattlevine22** [comment]
I'm using safari on OS X, but CIRCE (web version) appears to have been down since yesterday so I can't test on another machine/browser (actually, I ran into more issues on linux firefox). But you make a good point--I have some non-standard regional settings (the OS language is set to spanish and sometimes uses international-style date formats).

**Comment by mattlevine22** [comment]
update: I was able to reproduce this in Firefox on my linux machine at cumc dbmi, which doesn't have the suspicious international regional settings like my laptop. Perhaps you can check the example at http://www.ohdsi.org/web/circe/#/325 and try to change and save the date of "occurrence start is: On or After: YYYY-MM-DD"

**Comment by chrisknoll** [comment]
Hi,
  I pulled up the app in Firefox on Win32, and can see the issue, and I believe that it's an issue with date serialization:  we serialize the chosen date into yyyy-mm-dd as a string to put into the JSON object to save to the DB. Wen the object comes back, we Deserialize it assuming a yyyy-mm-dd format and then convert to a localized date.  Something in this process of searialization/deserialization is failing.  Works in Chrome tho.  Could you perahaps try in Chrome to see if it will work in your env as a temporary workaround, while I try to debug firefox and determine where the failure is happening?

**Comment by mattlevine22** [comment]
Thanks chris. It did indeed work for me in Chrome, both for OS X and ubuntu.

**Comment by chrisknoll** [comment]
Ok, I'm getting closer to the source of the issue:

On Chrome, this parses: new Date('2015-8-1'')
On Firefox, it parses into 'Invalid date'.  however, on Firefox, new Date('2015-08-01') does parse, so I need to pad the month and days to 2 digits for firefox compatability.

The issue is all the existing data out there that's been saved with the 1 digit date/month format. Firefox will not parse that properly.  So I may need to think longer about a longer term strategy.

**Comment by mattlevine22** [comment]
hopefully you don’t have to switch to multiple fields

**Comment by chrisknoll** [comment]
Ok, this is fixed for new saves, but you may run into an issue opening up existing cohort expressions that have been saved using the old date. The workaround is to open the old expressions, set the dates and save again.  This should let them be reloaded properly in the future
