### ISSUE TITLE
Import JSON button bug

### ISSUE THREAD

**Issue by mattlevine22** [OHDSI/Circe#44]
When importing a new concept with JSON, there are 2 Import buttons. Each produce a popup window for JSON entry, but the Done button only functions when using the top Import button. The bottom Import button brings the popup, but the Done button does not appear to work--the JSON popup remains open and the concept cannot be submitted.

**Comment by chrisknoll** [comment]
The bottom button 'import' is for importing a list of concept IDs. The top import button is for importing a json concept set expression.  

Most likely, an 'integer parse' error is occurring when you click the done button (from the bottom import button) and that's causing it to not close.  Error handling is defintiely a weakness in the current verson of circe.  There was some comments about making the top button 'Import Concept Set' and the bottom button 'Import Concept Id List' but these were pretty wordy....

**Comment by mattlevine22** [comment]
Ah, sorry, I didn’t realize the two Import buttons were different.
